"""empty message

Revision ID: 8b36820054fb
Revises: 67415fd63c19
Create Date: 2024-01-11 19:01:56.245005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b36820054fb'
down_revision = '67415fd63c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_add_column('items', schema=None) as batch_op:
        batch_op.add_column('includes',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('includes',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
